# Generated by Django 6.0.2 on 2026-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='fallos',
            field=models.IntegerField(default=0),
        ),
    ]
