# Generated by Django 6.0.2 on 2026-04-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_perfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='nivel_dificultad',
            field=models.CharField(default='basico', max_length=20),
        ),
        migrations.AddField(
            model_name='partida',
            name='nivel_maximo_alcanzado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partida',
            name='tiempo_reaccion_promedio',
            field=models.FloatField(default=0.0),
        ),
    ]
