# Generated by Django 6.0.2 on 2026-04-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_partida_nivel_dificultad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='estado_cognitivo',
            field=models.CharField(default='Sin datos', max_length=100),
        ),
    ]
