# Generated by Django 5.2.1 on 2026-08-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_consentimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consentimiento',
            old_name='fase',
            new_name='fase_otorgamiento',
        ),
        migrations.RenameField(
            model_name='consentimiento',
            old_name='type',
            new_name='tipo',
        ),
        migrations.AlterField(
            model_name='partida',
            name='tiempo_reaccion_promedio',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
