# Generated by Django 5.2.1 on 2026-08-28 00:35

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_paciente_profesional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nickname',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='El apodo solo puede contener letras, números, guion y guion bajo.', regex='^[A-Za-z0-9_-]+$')]),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('profesional', 'nickname'), name='unique_nickname_por_profesional'),
        ),
    ]
