# Generated by Django 5.2.1 on 2026-08-28 04:25

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_alter_paciente_nickname_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paciente',
            name='unique_nickname_por_profesional',
        ),
        migrations.AddField(
            model_name='paciente',
            name='codigo_publico',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pseudonimo_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nickname',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='profesional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('profesional', 'pseudonimo_hash'), name='unique_pseudonimo_por_profesional'),
        ),
    ]
