# Generated by Django 5.2.1 on 2026-09-23 19:06
import hashlib
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q

def preparar_datos_historicos(apps, schema_editor):
    Paciente = apps.get_model("games", "Paciente")
    User = apps.get_model("auth", "User")

    try:
        admin = User.objects.get(username="admin")
    except User.DoesNotExist:
        admin = None

    if admin is not None:
        Paciente.objects.filter(
            profesional_id=admin.id
        ).delete()
        
    pacientes_sin_hash = Paciente.objects.filter(
        Q(pseudonimo_hash__isnull=True)
        | Q(pseudonimo_hash="")
    )

    for paciente in pacientes_sin_hash:
        texto = f"legacy:{paciente.pk}"

        paciente.pseudonimo_hash = hashlib.sha256(
            texto.encode("utf-8")
        ).hexdigest()

        paciente.save(
            update_fields=["pseudonimo_hash"]
        )
        
class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_backfill_patient_pseudonyms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            preparar_datos_historicos,
            migrations.RunPython.noop,
        ),
        
        migrations.RemoveConstraint(
            model_name="paciente",
            name="unique_pseudonimo_por_profesional",
        ),

        migrations.RemoveField(
            model_name="paciente",
            name="nickname",
        ),

        migrations.RemoveField(
            model_name="paciente",
            name="user",
        ),

        migrations.AlterField(
            model_name="paciente",
            name="codigo_publico",
            field=models.CharField(
                editable=False,
                max_length=10,
                unique=True,
            ),
        ),

        migrations.AlterField(
            model_name="paciente",
            name="institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pacientes",
                to="games.institucion",
            ),
        ),

        migrations.AlterField(
            model_name="paciente",
            name="pseudonimo_hash",
            field=models.CharField(
                max_length=64,
            ),
        ),

        migrations.AlterField(
            model_name="partida",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partidas",
                to="games.paciente",
            ),
        ),

        migrations.AlterField(
            model_name="perfiles",
            name="institucion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="games.institucion",
            ),
        ),

        migrations.AddConstraint(
            model_name="paciente",
            constraint=models.UniqueConstraint(
                fields=(
                    "profesional",
                    "institucion",
                    "pseudonimo_hash",
                ),
                name="unique_pseudonimo_por_profesional",
            ),
        ),
    ]
