# Generated by Django 5.2.1 on 2026-09-23 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_backfill_patient_pseudonyms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paciente',
            name='unique_pseudonimo_por_profesional',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='codigo_publico',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pacientes', to='games.institucion'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='pseudonimo_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='partida',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='games.paciente'),
        ),
        migrations.AlterField(
            model_name='perfiles',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.institucion'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('profesional', 'institucion', 'pseudonimo_hash'), name='unique_pseudonimo_por_profesional'),
        ),
    ]
